[__config__]
oldver = "versions"
newver = "new_versions"

[greenclip]
source = "github"
github = "erebe/greenclip"
use_latest_release = true

[imgurbash2]
source = "github"
github = "ram-on/imgurbash2"
use_latest_release = true

[neovim]
source = "github"
github = "neovim/neovim"
use_latest_release = true

[rofi-pass]
source = "github"
github = "carnager/rofi-pass"
use_latest_release = true

[st]
source = "regex"
url = "https://dl.suckless.org/st/"
regex = "st-([0-9.]+).tar.gz"

[heyteiler]
source = "github"
github = "HeyLazySunnyKid/heyteiler"
use_latest_release = true

[xininfo]
source = "github"
github = "DaveDavenport/xininfo"
branch = "master"

[tmux]
source = "github"
github = "tmux/tmux"
use_latest_release = true

[direnv]
source = "github"
github = "direnv/direnv"
use_latest_release = true

[xkblayout-state]
source = "github"
github = "nonpop/xkblayout-state"
branch = "master"

[xmapnotify]
source = "github"
github = "HeyLazySunnyKid/xmapnotify"
branch = "main"
